# Generated by Django 4.2.1 on 2023-06-01 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('fullname', models.CharField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('emp_code', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
